version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: talk2dom-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: talk2dom
    volumes:
      - postgres_data:/var/lib/postgresql/data

  talk2dom-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: