# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: talk2dom-service
spec:
  selector:
    app: talk2dom-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer